Try and upate CODECOV-check.yml

diff --git a/.github/workflows/CODECOV-check.yml b/.github/workflows/CODECOV-check.yml
--- a/.github/workflows/CODECOV-check.yml
+++ b/.github/workflows/CODECOV-check.yml
@@ -11,8 +11,7 @@ on:
 # Increment this version when we want to clear cache
 env:
   cache-version: v1
-  r-version: 4.6.1
-
+  
 jobs:
   CODECOV-check:
     runs-on: ubuntu-latest
@@ -22,42 +21,79 @@ jobs:
       
     steps:
       - uses: actions/checkout@v4
-        with:
-          r-version: ${{ env.r-version }}
 
       - uses: r-lib/actions/setup-r@v2
-
-      - uses: r-lib/actions/setup-pandoc@v2
-
-      - name: Query dependencies
-        run: |
-          install.packages('remotes')
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
-        shell: Rscript {0}
-
-      - name: Cache R packages
-        uses: actions/cache@v3
         with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ env.cache-version }}-${{ runner.os }}-${{ env.r-version }}-${{ hashFiles('.github/depends.Rds') }}
-          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-${{ env.r-version }}-
+          use-public-rspm: true
+
+      - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: any::covr, any::xml2
+          needs: coverage
           
-      - name: Install system dependencies on Linux
-        run: |
-          sudo apt install libgdal-dev libproj-dev libgeos-dev libudunits2-dev libgfortran5
-          while read -r cmd
-          do
-            eval sudo $cmd
-          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')
-
-      - name: Install dependencies
-        run: |
-          remotes::install_deps(dependencies = TRUE)
-          remotes::install_cran("covr")
-        shell: Rscript {0}
-
       - name: Test coverage
         run: |
-          R CMD INSTALL .
-          Rscript -e 'covr::codecov()'
+          cov <- covr::package_coverage(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          print(cov)
+          covr::to_cobertura(cov)
+        shell: Rscript {0}
+
+      - uses: codecov/codecov-action@v5
+        with:
+          # Fail if error if not on PR, or if on PR and token is given
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
+          files: ./cobertura.xml
+          plugins: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
+
+      # - name: Query dependencies
+      #   run: |
+      #     install.packages('remotes')
+      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
+      #   shell: Rscript {0}
+      # 
+      # - name: Cache R packages
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ${{ env.R_LIBS_USER }}
+      #     key: ${{ env.cache-version }}-${{ runner.os }}-${{ env.r-version }}-${{ hashFiles('.github/depends.Rds') }}
+      #     restore-keys: ${{ env.cache-version }}-${{ runner.os }}-${{ env.r-version }}-
+      #     
+      # - name: Install system dependencies on Linux
+      #   run: |
+      #     sudo apt install libgdal-dev libproj-dev libgeos-dev libudunits2-dev libgfortran5
+      #     while read -r cmd
+      #     do
+      #       eval sudo $cmd
+      #     done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')
+      # 
+      # - name: Install dependencies
+      #   run: |
+      #     remotes::install_deps(dependencies = TRUE)
+      #     remotes::install_cran("covr")
+      #   shell: Rscript {0}
+      # 
+      # - name: Test coverage
+      #   run: |
+      #     R CMD INSTALL .
+      #     Rscript -e 'covr::codecov()'
           
